/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demineur_1_peron;

import javax.swing.JButton;

import java.awt.GridLayout;

/**
 *
 * @author eliot
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    GrilleDeJeu grille;

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();

        initialiserPartieParDefaut();

        PanneauGrille.setVisible(false);
        Rejouer.setVisible(false);
        information.setVisible(false);

    }

    private void initialiserPartieParDefaut() {
        configurerGrille(5, 5, 5); // Niveau 1 par défaut
    }

    private void configurerGrille(int nbLignes, int nbColonnes, int nbBombe) {
        grille = new GrilleDeJeu(nbLignes, nbColonnes, nbBombe);
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
        PanneauGrille.removeAll(); // Nettoie les cellules précédentes

        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                CelluleGraphique bouton_cellule = new CelluleGraphique(grille.matriceCellules[i][j], 36, 36);
                PanneauGrille.add(bouton_cellule);
            }
        }

        PanneauGrille.revalidate(); // Actualise l'affichage
        PanneauGrille.repaint();
    }

    private void verifierFinDePartie() {
        if (grille.toutesCellulesRevelees()) {
            System.out.println("Félicitations, vous avez gagné !");
            // Optionnel : Afficher une boîte de dialogue
            javax.swing.JOptionPane.showMessageDialog(this, "Vous avez gagné !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        PanneauGrille = new javax.swing.JPanel();
        Panneau_info_joueur = new javax.swing.JPanel();
        jButtonNiveau1 = new javax.swing.JButton();
        jButtonNiveau2 = new javax.swing.JButton();
        jButtonNiveau3 = new javax.swing.JButton();
        régles = new javax.swing.JButton();
        information = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Rejouer = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(0, 0, 255));
        PanneauGrille.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PanneauGrille.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 700, 700));

        Panneau_info_joueur.setBackground(new java.awt.Color(204, 255, 204));
        Panneau_info_joueur.setForeground(new java.awt.Color(153, 153, 153));
        Panneau_info_joueur.setLayout(new java.awt.GridLayout(1, 0));

        jButtonNiveau1.setText("niveau 1");
        jButtonNiveau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveau1ActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(jButtonNiveau1);

        jButtonNiveau2.setText("niveau 2");
        jButtonNiveau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveau2ActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(jButtonNiveau2);

        jButtonNiveau3.setText("niveau 3");
        jButtonNiveau3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveau3ActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(jButtonNiveau3);

        régles.setText("régles");
        régles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                réglesActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(régles);

        getContentPane().add(Panneau_info_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 400, 100));

        information.setBackground(new java.awt.Color(0, 0, 255));
        information.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        information.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("information du jeux  ");
        information.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("clique gauche = decouverte de case ");
        information.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("clique droit = drapeau  ⚑");
        information.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        Rejouer.setText("Rejouer");
        Rejouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejouerActionPerformed(evt);
            }
        });
        information.add(Rejouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        getContentPane().add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 280, 160));

        setBounds(0, 0, 1130, 839);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNiveau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveau1ActionPerformed
        // TODO add your handling code here:

        PanneauGrille.setVisible(true);

        Panneau_info_joueur.setVisible(false);
        configurerGrille(5, 5, 5); // Niveau 1 : 5x5 grille, 5 bombes
        Rejouer.setVisible(true);
        information.setVisible(true);


    }//GEN-LAST:event_jButtonNiveau1ActionPerformed

    private void jButtonNiveau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveau2ActionPerformed
        // TODO add your handling code here:
        PanneauGrille.setVisible(true);

        Panneau_info_joueur.setVisible(false);
        configurerGrille(10, 10, 20); // Niveau 1 : 5x5 grille, 5 bombes
        Rejouer.setVisible(true);
        information.setVisible(true);

    }//GEN-LAST:event_jButtonNiveau2ActionPerformed

    private void jButtonNiveau3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveau3ActionPerformed
        // TODO add your handling code here:
        PanneauGrille.setVisible(true);

        Panneau_info_joueur.setVisible(false);
        configurerGrille(20, 20, 40); // Niveau 1 : 5x5 grille, 5 bombes
        Rejouer.setVisible(true);
        information.setVisible(true);

    }//GEN-LAST:event_jButtonNiveau3ActionPerformed

    private void RejouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejouerActionPerformed
        // TODO add your handling code here:
        initialiserPartieParDefaut(); // Réinitialise la partie
        Panneau_info_joueur.setVisible(true); // Rend le panneau visible
        PanneauGrille.setVisible(false); // Cache la grille de jeu
        Panneau_info_joueur.revalidate(); // Actualise le panneau
    }//GEN-LAST:event_RejouerActionPerformed

    private void réglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_réglesActionPerformed
        String messageRegles = """
    Bienvenue dans le jeu Démineur !

    Objectif :
    - Dévoilez toutes les cases sans exploser de bombes.

    Commandes :
    - Cliquez avec le bouton droit pour marquer une case avec un drapeau (⚑).
    - Cliquez avec le bouton gauche pour révéler une case.

    Conseils :
    - Les numéros affichés sur les cases révèlent combien de bombes se trouvent dans les cases adjacentes.
    - Utilisez ces indices pour déduire les positions des bombes.

    Bonne chance !
    """;
        javax.swing.JOptionPane.showMessageDialog(this, messageRegles, "Règles du jeu", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_réglesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JPanel Panneau_info_joueur;
    private javax.swing.JButton Rejouer;
    private javax.swing.JPanel information;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNiveau1;
    private javax.swing.JButton jButtonNiveau2;
    private javax.swing.JButton jButtonNiveau3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton régles;
    // End of variables declaration//GEN-END:variables
}
///ZER
