/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demineur_1_peron;

import java.awt.GridLayout;

/**
 *
 * @author eliot
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    GrilleDeJeu grille;

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();

        initialiserPartieParDefaut();

        PanneauGrille.setVisible(false);
        Rejouer.setVisible(false);
        information.setVisible(false);

    }

    private void initialiserPartieParDefaut() {
        configurerGrille(5, 5, 5); // Niveau 1 par défaut
    }
    
    
    

    private void configurerGrille(int nbLignes, int nbColonnes, int nbBombe) {
        grille = new GrilleDeJeu(nbLignes, nbColonnes, nbBombe);
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
        PanneauGrille.removeAll(); // Nettoie les cellules précédentes

        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                CelluleGraphique bouton_cellule = new CelluleGraphique(grille.matriceCellules[i][j], 36, 36);
                PanneauGrille.add(bouton_cellule);
            }
        }

        PanneauGrille.revalidate(); // Actualise l'affichage
        PanneauGrille.repaint();
    }

    public void terminerPartie(boolean victoire) {
        // Désactiver toutes les cellules
        for (int i = 0; i < grille.matriceCellules.length; i++) {
            for (int j = 0; j < grille.matriceCellules[i].length; j++) {
                CelluleGraphique bouton_cellule = (CelluleGraphique) PanneauGrille.getComponent(i * grille.matriceCellules[i].length + j);
                bouton_cellule.setEnabled(false);
            }
        }

        // Afficher un message de fin
        String message = victoire
                ? "Félicitations ! Vous avez gagné !go aller au bar lets go bahahahahah "
                : "Vous avez cliqué sur une bombe ! Emoji tete de mort fini dans le game bye bitch.";
        javax.swing.JOptionPane.showMessageDialog(this, message, "Fin de partie", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Réinitialiser la partie dans les deux cas
        initialiserPartieParDefaut();
        Panneau_info_joueur.setVisible(true);
        PanneauGrille.setVisible(false);
        information.setVisible(false);
        Panneau_info_joueur.revalidate();
        Panneau_info_joueur.repaint();
        
        
    }

    public void verifierVictoire() {
        for (int i = 0; i < grille.matriceCellules.length; i++) {
            for (int j = 0; j < grille.matriceCellules[i].length; j++) {
                Cellule cellule = grille.matriceCellules[i][j];
                if (!cellule.getPresenceBombe() && !cellule.isDevoilee()) {
                    return; // Il reste des cases à découvrir
                }
            }
        }

        // Si toutes les cases non-bombes sont révélées, la partie est gagnée
        terminerPartie(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PanneauGrille = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Panneau_info_joueur = new javax.swing.JPanel();
        jButtonNiveau1 = new javax.swing.JButton();
        jButtonNiveau2 = new javax.swing.JButton();
        jButtonNiveau3 = new javax.swing.JButton();
        choix_niveau = new javax.swing.JButton();
        régles = new javax.swing.JButton();
        information = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Rejouer = new javax.swing.JButton();
        nomination = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(255, 0, 0));
        PanneauGrille.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PanneauGrille.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanneauGrille.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -40, -1, -1));

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 700, 700));

        Panneau_info_joueur.setBackground(new java.awt.Color(255, 0, 51));
        Panneau_info_joueur.setForeground(new java.awt.Color(153, 153, 153));
        Panneau_info_joueur.setLayout(new java.awt.GridLayout());

        jButtonNiveau1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNiveau1.setForeground(new java.awt.Color(255, 0, 0));
        jButtonNiveau1.setText("niveau 1");
        jButtonNiveau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveau1ActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(jButtonNiveau1);

        jButtonNiveau2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNiveau2.setForeground(new java.awt.Color(255, 0, 0));
        jButtonNiveau2.setText("niveau 2");
        jButtonNiveau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveau2ActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(jButtonNiveau2);

        jButtonNiveau3.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNiveau3.setForeground(new java.awt.Color(255, 0, 0));
        jButtonNiveau3.setText("niveau 3");
        jButtonNiveau3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveau3ActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(jButtonNiveau3);

        choix_niveau.setBackground(new java.awt.Color(0, 0, 0));
        choix_niveau.setForeground(new java.awt.Color(255, 0, 0));
        choix_niveau.setText("choix");
        choix_niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix_niveauActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(choix_niveau);

        régles.setBackground(new java.awt.Color(0, 0, 0));
        régles.setForeground(new java.awt.Color(255, 0, 0));
        régles.setText("règles");
        régles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                réglesActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(régles);

        getContentPane().add(Panneau_info_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 400, 100));

        information.setBackground(new java.awt.Color(255, 0, 0));
        information.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        information.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Information de jeu  ");
        information.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Clique gauche = découverte d'une case ");
        information.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Clique droit = drapeau  ");
        information.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        Rejouer.setBackground(new java.awt.Color(0, 0, 0));
        Rejouer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Rejouer.setForeground(new java.awt.Color(255, 0, 0));
        Rejouer.setText("MENU");
        Rejouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejouerActionPerformed(evt);
            }
        });
        information.add(Rejouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, 30));

        getContentPane().add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 280, 160));

        nomination.setBackground(new java.awt.Color(255, 0, 51));
        nomination.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("- Leobz la street de Marseille");
        nomination.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("- Eliott le bg du 69");
        nomination.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("💣 Jeu du démineur 💣");
        nomination.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel7.setText("Créateurs:");
        nomination.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        getContentPane().add(nomination, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 400, 90));

        setBounds(0, 0, 1096, 1525);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNiveau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveau1ActionPerformed
        // TODO add your handling code here:

        PanneauGrille.setVisible(true);

        Panneau_info_joueur.setVisible(false);
        configurerGrille(5, 5, 5);
        Rejouer.setVisible(true);
        information.setVisible(true);


    }//GEN-LAST:event_jButtonNiveau1ActionPerformed

    private void jButtonNiveau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveau2ActionPerformed
        // TODO add your handling code here:
        PanneauGrille.setVisible(true);

        Panneau_info_joueur.setVisible(false);
        configurerGrille(10, 10, 20);
        Rejouer.setVisible(true);
        information.setVisible(true);

    }//GEN-LAST:event_jButtonNiveau2ActionPerformed

    private void jButtonNiveau3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveau3ActionPerformed
        // TODO add your handling code here:
        PanneauGrille.setVisible(true);

        Panneau_info_joueur.setVisible(false);
        configurerGrille(15, 15, 30);
        Rejouer.setVisible(true);
        information.setVisible(true);

    }//GEN-LAST:event_jButtonNiveau3ActionPerformed

    private void RejouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejouerActionPerformed
        initialiserPartieParDefaut();

        // Affiche le menu avec les niveaux
        Panneau_info_joueur.setVisible(true);

        // Cache la grille de jeu
        PanneauGrille.setVisible(false);

        // Cache le panneau d'informations du jeu
        information.setVisible(false);

        // Réactualise l'interface pour s'assurer que tout est correctement affiché
        Panneau_info_joueur.revalidate();
        Panneau_info_joueur.repaint();
    }//GEN-LAST:event_RejouerActionPerformed

    private void réglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_réglesActionPerformed
        String messageRegles = """
    Bienvenue dans le jeu Démineur !

    Objectif :
    - Dévoilez toutes les cases sans exploser de bombes.

    Commandes :
    - Cliquez avec le bouton droit pour marquer une case avec un drapeau (⚑).
    - Cliquez avec le bouton gauche pour révéler une case.

    Conseils :
    - Les numéros affichés sur les cases révèlent combien de bombes se trouvent dans les cases adjacentes.
    - Utilisez ces indices pour déduire les positions des bombes.

    Bonne chance !
    """;
        javax.swing.JOptionPane.showMessageDialog(this, messageRegles, "Règles du jeu", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_réglesActionPerformed

    private void choix_niveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix_niveauActionPerformed

        try {
            // Demande la saisie des dimensions de la grille et du nombre de bombes
            String inputA = javax.swing.JOptionPane.showInputDialog(this, "Entrez le nombre de lignes :", "Choix du niveau", javax.swing.JOptionPane.QUESTION_MESSAGE);
            String inputB = javax.swing.JOptionPane.showInputDialog(this, "Entrez le nombre de colonnes :", "Choix du niveau", javax.swing.JOptionPane.QUESTION_MESSAGE);
            String inputC = javax.swing.JOptionPane.showInputDialog(this, "Entrez le nombre de bombes :", "Choix du niveau", javax.swing.JOptionPane.QUESTION_MESSAGE);

            // Conversion des entrées en entiers
            int a = Integer.parseInt(inputA);
            int b = Integer.parseInt(inputB);
            int c = Integer.parseInt(inputC);

            // Validation des données
            if (a <= 0 || b <= 0 || c <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Les valeurs doivent être positives !", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (c >= a * b) {
                javax.swing.JOptionPane.showMessageDialog(this, "Le nombre de bombes doit être inférieur au nombre total de cases !", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Configuration de la grille avec les paramètres saisis
            PanneauGrille.setVisible(true);
            Panneau_info_joueur.setVisible(false);
            configurerGrille(a, b, c);
            Rejouer.setVisible(true);
            information.setVisible(true);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Veuillez entrer des nombres valides !", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_choix_niveauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JPanel Panneau_info_joueur;
    private javax.swing.JButton Rejouer;
    private javax.swing.JButton choix_niveau;
    private javax.swing.JPanel information;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNiveau1;
    private javax.swing.JButton jButtonNiveau2;
    private javax.swing.JButton jButtonNiveau3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel nomination;
    private javax.swing.JButton régles;
    // End of variables declaration//GEN-END:variables
}
///ZER
