/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demineur_1_peron;

import javax.swing.JButton;

import java.awt.GridLayout;

/**
 *
 * @author eliot
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    GrilleDeJeu grille;

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();

        PanneauGrille.setVisible(false);
      

        initialiserPartieParDefaut();

    }

    private void initialiserPartieParDefaut() {
        configurerGrille(5, 5, 5); // Niveau 1 par défaut
    }

    private void configurerGrille(int nbLignes, int nbColonnes, int nbBombe) {
        grille = new GrilleDeJeu(nbLignes, nbColonnes, nbBombe);
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
        PanneauGrille.removeAll(); // Nettoie les cellules précédentes

        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                CelluleGraphique bouton_cellule = new CelluleGraphique(grille.matriceCellules[i][j], 36, 36);
                PanneauGrille.add(bouton_cellule);
            }
        }

        grille.placerBombesAleatoirement();
        PanneauGrille.revalidate(); // Actualise l'affichage
        PanneauGrille.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        PanneauGrille = new javax.swing.JPanel();
        Panneau_info_joueur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonNiveau1 = new javax.swing.JButton();
        jButtonNiveau2 = new javax.swing.JButton();
        jButtonNiveau3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(255, 255, 0));
        PanneauGrille.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 700, 700));

        Panneau_info_joueur.setBackground(new java.awt.Color(204, 255, 204));
        Panneau_info_joueur.setForeground(new java.awt.Color(153, 153, 153));
        Panneau_info_joueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("niveau 1 ");
        Panneau_info_joueur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 40));

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("niveau 3");
        Panneau_info_joueur.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, 20));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("niveau 2");
        Panneau_info_joueur.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 40));

        jButtonNiveau1.setText("OK");
        jButtonNiveau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveau1ActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(jButtonNiveau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jButtonNiveau2.setText("OK");
        jButtonNiveau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveau2ActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(jButtonNiveau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jButtonNiveau3.setText("OK");
        jButtonNiveau3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveau3ActionPerformed(evt);
            }
        });
        Panneau_info_joueur.add(jButtonNiveau3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        getContentPane().add(Panneau_info_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 250, 130));

        setBounds(0, 0, 930, 841);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNiveau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveau1ActionPerformed
        // TODO add your handling code here:

        PanneauGrille.setVisible(true);
       
        Panneau_info_joueur.setVisible(false);
         configurerGrille(5, 5, 5); // Niveau 1 : 5x5 grille, 5 bombes


    }//GEN-LAST:event_jButtonNiveau1ActionPerformed

    private void jButtonNiveau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveau2ActionPerformed
        // TODO add your handling code here:
        PanneauGrille.setVisible(true);
        
        Panneau_info_joueur.setVisible(false);
         configurerGrille(10, 10, 20); // Niveau 1 : 5x5 grille, 5 bombes
    }//GEN-LAST:event_jButtonNiveau2ActionPerformed

    private void jButtonNiveau3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveau3ActionPerformed
        // TODO add your handling code here:
        PanneauGrille.setVisible(true);
        
        Panneau_info_joueur.setVisible(false);
         configurerGrille(20, 20, 40); // Niveau 1 : 5x5 grille, 5 bombes
    }//GEN-LAST:event_jButtonNiveau3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JPanel Panneau_info_joueur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNiveau1;
    private javax.swing.JButton jButtonNiveau2;
    private javax.swing.JButton jButtonNiveau3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
